import { UserType } from "@/components/usecase/useUserList";

export const dummyUsers: UserType[] = [
  {
    id: "1",
    userId: "user01",
    password: "password01",
    userName: "User One",
    birthday: "1990-01-01",
    age: 30,
    gender: 1,
    genderName: "男性",
    profile: "Profile of User One",
    department: {
      departmentId: 1,
      departmentName: "開発部",
    },
  },
  {
    id: "2",
    userId: "user02",
    password: "password01",
    userName: "User Two",
    birthday: "1990-01-01",
    age: 30,
    gender: 2,
    genderName: "女性",
    profile: "Profile of User One",
    department: {
      departmentId: 2,
      departmentName: "営業部",
    },
  },
  {
    id: "3",
    userId: "system03",
    password: "password01",
    userName: "User 3",
    birthday: "1990-01-01",
    age: 30,
    gender: 1,
    genderName: "男性",
    profile: "Profile of User One",
    department: {
      departmentId: 1,
      departmentName: "開発部",
    },
  },
  {
    id: "4",
    userId: "user04",
    password: "password01",
    userName: "User 4",
    birthday: "1990-01-01",
    age: 30,
    gender: 1,
    genderName: "男性",
    profile: "Profile of User One",
    department: {
      departmentId: 2,
      departmentName: "営業部",
    },
  },
  {
    id: "5",
    userId: "user05",
    password: "password01",
    userName: "User 5",
    birthday: "1990-01-01",
    age: 30,
    gender: 1,
    genderName: "男性",
    profile: "Profile of User One",
    department: {
      departmentId: 2,
      departmentName: "営業部",
    },
  },
  {
    id: "6",
    userId: "system06",
    password: "password01",
    userName: "User 6",
    birthday: "1990-01-01",
    age: 30,
    gender: 3,
    genderName: "その他",
    profile: "Profile of User One",
    department: {
      departmentId: 1,
      departmentName: "開発部",
    },
  },
  {
    id: "7",
    userId: "user7",
    password: "password7",
    userName: "User user7",
    birthday: "1993-03-25",
    age: 31,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user7",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "8",
    userId: "user8",
    password: "password8",
    userName: "User user8",
    birthday: "1986-03-27",
    age: 38,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user8",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "9",
    userId: "user9",
    password: "password9",
    userName: "User user9",
    birthday: "1997-03-24",
    age: 27,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user9",
    department: { departmentId: 2, departmentName: "営業部" },
  },
  {
    id: "10",
    userId: "user10",
    password: "password10",
    userName: "User user10",
    birthday: "1953-04-04",
    age: 71,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user10",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "11",
    userId: "user11",
    password: "password11",
    userName: "User user11",
    birthday: "1948-04-05",
    age: 76,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user11",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "12",
    userId: "user12",
    password: "password12",
    userName: "User user12",
    birthday: "2001-03-23",
    age: 23,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user12",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "13",
    userId: "user13",
    password: "password13",
    userName: "User user13",
    birthday: "1945-04-06",
    age: 79,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user13",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "14",
    userId: "user14",
    password: "password14",
    userName: "User user14",
    birthday: "1975-03-30",
    age: 49,
    gender: 1,
    genderName: "男性",
    profile: "Profile of user user14",
    department: { departmentId: 3, departmentName: "管理本部" },
  },
  {
    id: "15",
    userId: "user15",
    password: "password15",
    userName: "User user15",
    birthday: "1946-04-06",
    age: 78,
    gender: 1,
    genderName: "男性",
    profile: "Profile of user user15",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "16",
    userId: "user16",
    password: "password16",
    userName: "User user16",
    birthday: "1986-03-27",
    age: 38,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user16",
    department: { departmentId: 3, departmentName: "管理本部" },
  },
  {
    id: "17",
    userId: "user17",
    password: "password17",
    userName: "User user17",
    birthday: "1981-03-28",
    age: 43,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user17",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "18",
    userId: "user18",
    password: "password18",
    userName: "User user18",
    birthday: "1961-04-02",
    age: 63,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user18",
    department: { departmentId: 3, departmentName: "管理本部" },
  },
  {
    id: "19",
    userId: "user19",
    password: "password19",
    userName: "User user19",
    birthday: "1955-04-04",
    age: 69,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user19",
    department: { departmentId: 3, departmentName: "管理本部" },
  },
  {
    id: "20",
    userId: "user20",
    password: "password20",
    userName: "User user20",
    birthday: "1988-03-26",
    age: 36,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user20",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "21",
    userId: "user21",
    password: "password21",
    userName: "User user21",
    birthday: "1991-03-26",
    age: 33,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user21",
    department: { departmentId: 2, departmentName: "営業部" },
  },
  {
    id: "22",
    userId: "user22",
    password: "password22",
    userName: "User user22",
    birthday: "1996-03-24",
    age: 28,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user22",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "23",
    userId: "user23",
    password: "password23",
    userName: "User user23",
    birthday: "1957-04-03",
    age: 67,
    gender: 1,
    genderName: "男性",
    profile: "Profile of user user23",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "24",
    userId: "user24",
    password: "password24",
    userName: "User user24",
    birthday: "1961-04-02",
    age: 63,
    gender: 1,
    genderName: "男性",
    profile: "Profile of user user24",
    department: { departmentId: 1, departmentName: "開発部" },
  },
  {
    id: "25",
    userId: "user25",
    password: "password25",
    userName: "User user25",
    birthday: "1965-04-01",
    age: 59,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user25",
    department: { departmentId: 2, departmentName: "営業部" },
  },
  {
    id: "26",
    userId: "user26",
    password: "password26",
    userName: "User user26",
    birthday: "1973-03-30",
    age: 51,
    gender: 2,
    genderName: "女性",
    profile: "Profile of user user26",
    department: { departmentId: 1, departmentName: "開発部" },
  },
];
